import type { Priority } from '../types/index.js';

export type SeoImportance = 'high' | 'medium' | 'low';

/** A known page's definition — its purpose and the sections/components it is built from. */
export interface PageDefinition {
  readonly name: string;
  readonly purpose: string;
  readonly priority: Priority;
  readonly seoImportance: SeoImportance;
  readonly sections: readonly string[];
  /** Design-system component ids this page composes. */
  readonly components: readonly string[];
}

const def = (
  name: string,
  purpose: string,
  priority: Priority,
  seoImportance: SeoImportance,
  sections: readonly string[],
  components: readonly string[],
): PageDefinition => ({ name, purpose, priority, seoImportance, sections, components });

/** Definitions for every page the planner knows how to specify. */
export const PAGE_CATALOG: Readonly<Record<string, PageDefinition>> = {
  home: def(
    'Home',
    'Communicate the core value and route visitors to conversion.',
    'critical',
    'high',
    ['hero', 'value', 'proof', 'features', 'cta'],
    ['navbar', 'hero', 'features', 'testimonials', 'cta', 'footer'],
  ),
  about: def(
    'About',
    'Build trust through story, team, and credibility.',
    'high',
    'medium',
    ['story', 'team', 'values'],
    ['navbar', 'team', 'stats', 'cta', 'footer'],
  ),
  services: def(
    'Services',
    'Explain offerings and their outcomes.',
    'high',
    'high',
    ['overview', 'service-detail', 'cta'],
    ['navbar', 'features', 'cta', 'footer'],
  ),
  'practice-areas': def(
    'Practice Areas',
    'Detail legal practice areas and outcomes.',
    'high',
    'high',
    ['areas', 'results', 'cta'],
    ['navbar', 'features', 'testimonials', 'cta', 'footer'],
  ),
  pricing: def(
    'Pricing',
    'Present plans and drive the purchase decision.',
    'high',
    'high',
    ['tiers', 'comparison', 'faq'],
    ['navbar', 'pricing', 'faq', 'cta', 'footer'],
  ),
  'case-studies': def(
    'Case Studies',
    'Prove results with real client stories.',
    'high',
    'high',
    ['listing', 'detail'],
    ['navbar', 'card', 'testimonials', 'cta', 'footer'],
  ),
  portfolio: def(
    'Portfolio',
    'Showcase work to establish craft.',
    'high',
    'medium',
    ['gallery', 'detail'],
    ['navbar', 'gallery', 'cta', 'footer'],
  ),
  work: def(
    'Work',
    'Showcase selected projects.',
    'high',
    'medium',
    ['gallery', 'detail'],
    ['navbar', 'gallery', 'cta', 'footer'],
  ),
  blog: def(
    'Blog',
    'Publish content for SEO and authority.',
    'medium',
    'high',
    ['listing', 'article'],
    ['navbar', 'blog-card', 'footer'],
  ),
  faq: def(
    'FAQ',
    'Answer objections and aid discoverability.',
    'medium',
    'high',
    ['questions'],
    ['navbar', 'faq', 'footer'],
  ),
  contact: def(
    'Contact',
    'Capture inquiries and provide details.',
    'high',
    'medium',
    ['form', 'details'],
    ['navbar', 'contact', 'form', 'footer'],
  ),
  team: def(
    'Team',
    'Introduce the people behind the work.',
    'medium',
    'low',
    ['members'],
    ['navbar', 'team', 'footer'],
  ),
  features: def(
    'Features',
    'Detail product capabilities.',
    'high',
    'high',
    ['feature-detail'],
    ['navbar', 'features', 'cta', 'footer'],
  ),
  docs: def(
    'Documentation',
    'Reference material for the product.',
    'medium',
    'medium',
    ['nav', 'reference'],
    ['navbar', 'admin', 'faq', 'footer'],
  ),
  products: def(
    'Products',
    'Browse the catalog.',
    'critical',
    'high',
    ['grid', 'filters'],
    ['navbar', 'commerce', 'footer'],
  ),
  'product-detail': def(
    'Product Detail',
    'Convert a browser into a buyer.',
    'high',
    'high',
    ['gallery', 'details', 'related'],
    ['navbar', 'commerce', 'testimonials', 'footer'],
  ),
  cart: def(
    'Cart',
    'Review the selection before checkout.',
    'high',
    'low',
    ['line-items', 'summary'],
    ['navbar', 'commerce', 'footer'],
  ),
  checkout: def(
    'Checkout',
    'Complete the purchase securely.',
    'critical',
    'low',
    ['form', 'summary'],
    ['navbar', 'commerce', 'form', 'footer'],
  ),
  account: def(
    'Account',
    'Manage orders and profile.',
    'medium',
    'low',
    ['profile', 'orders'],
    ['admin', 'form'],
  ),
  courses: def(
    'Courses',
    'Browse and enroll in courses.',
    'critical',
    'high',
    ['catalog', 'detail'],
    ['navbar', 'card', 'pricing', 'footer'],
  ),
  listings: def(
    'Listings',
    'Search and filter properties.',
    'critical',
    'high',
    ['search', 'grid', 'map'],
    ['navbar', 'commerce', 'chart', 'footer'],
  ),
  'property-detail': def(
    'Property Detail',
    'Present a property and capture interest.',
    'high',
    'high',
    ['gallery', 'details', 'inquiry'],
    ['navbar', 'gallery', 'contact', 'footer'],
  ),
  menu: def(
    'Menu',
    'Present the offering.',
    'high',
    'high',
    ['sections', 'items'],
    ['navbar', 'features', 'footer'],
  ),
  gallery: def(
    'Gallery',
    'Show the space or work visually.',
    'medium',
    'medium',
    ['grid'],
    ['navbar', 'gallery', 'footer'],
  ),
  reservations: def(
    'Reservations',
    'Capture bookings.',
    'critical',
    'medium',
    ['form'],
    ['navbar', 'contact', 'form', 'footer'],
  ),
  appointments: def(
    'Appointments',
    'Book time with a provider.',
    'critical',
    'medium',
    ['booking'],
    ['navbar', 'contact', 'form', 'footer'],
  ),
  programs: def(
    'Programs',
    'Describe programs and impact.',
    'high',
    'high',
    ['overview', 'detail'],
    ['navbar', 'features', 'stats', 'footer'],
  ),
  impact: def(
    'Impact',
    'Demonstrate outcomes and transparency.',
    'high',
    'medium',
    ['metrics', 'stories'],
    ['navbar', 'stats', 'testimonials', 'footer'],
  ),
  donate: def(
    'Donate',
    'Convert supporters into donors.',
    'critical',
    'medium',
    ['form', 'impact'],
    ['navbar', 'form', 'cta', 'footer'],
  ),
  resources: def(
    'Resources',
    'Provide helpful guides and tools.',
    'medium',
    'high',
    ['listing'],
    ['navbar', 'blog-card', 'footer'],
  ),
  dashboard: def(
    'Dashboard',
    'The authenticated application home.',
    'critical',
    'low',
    ['metrics', 'activity'],
    ['admin', 'dashboard-widget', 'chart', 'table'],
  ),
  admin: def(
    'Admin',
    'Back-office management.',
    'high',
    'low',
    ['data', 'management'],
    ['admin', 'table', 'dashboard-widget'],
  ),
  login: def('Login', 'Authenticate returning users.', 'high', 'low', ['form'], ['auth', 'form']),
  signup: def('Sign Up', 'Register new users.', 'critical', 'low', ['form'], ['auth', 'form']),
  attorneys: def(
    'Attorneys',
    'Introduce the legal team and credentials.',
    'high',
    'medium',
    ['members'],
    ['navbar', 'team', 'footer'],
  ),
  legal: def('Legal', 'Required legal and policy pages.', 'medium', 'low', ['policy'], ['footer']),
};
