import type { IndustryProfile } from './types.js';

/** The always-present fallback profile, used when no industry keyword matches. */
export const GENERIC_PROFILE: IndustryProfile = {
  id: 'generic',
  name: 'General Business',
  keywords: [],
  businessModels: ['product', 'service'],
  typicalPages: ['home', 'about', 'services', 'blog', 'contact'],
  typicalFeatures: ['contact-forms', 'newsletter', 'analytics'],
  trustSignals: ['testimonials', 'about story', 'contact details'],
  seoTopics: ['core offering', 'about content', 'local SEO'],
  competitorNavigation: ['Home', 'About', 'Services', 'Blog', 'Contact'],
  contentOpportunities: ['service pages', 'about page', 'blog'],
  conversions: ['contact form', 'newsletter signup'],
  valuePropositions: ['quality offering', 'trusted service', 'clear value'],
};

/**
 * The industry knowledge base. Each profile encodes structured best practices for a sector —
 * expected pages, features, trust signals, SEO topics, competitor patterns, and conversions.
 * This is the deterministic source planners consult; nothing here is scraped from live sites.
 */
export const INDUSTRY_CATALOG: readonly IndustryProfile[] = [
  {
    id: 'saas',
    name: 'SaaS / Software',
    keywords: ['saas', 'software', 'platform', 'app', 'dashboard', 'api', 'tool', 'subscription'],
    businessModels: ['subscription', 'freemium', 'usage-based'],
    typicalPages: [
      'home',
      'features',
      'pricing',
      'about',
      'blog',
      'docs',
      'contact',
      'login',
      'signup',
    ],
    typicalFeatures: ['authentication', 'payments', 'search', 'analytics', 'newsletter', 'admin'],
    trustSignals: [
      'customer logos',
      'testimonials',
      'security badges',
      'uptime status',
      'case studies',
    ],
    seoTopics: ['product category', 'use cases', 'comparisons', 'integrations', 'how-to guides'],
    competitorNavigation: ['Product', 'Solutions', 'Pricing', 'Resources', 'Docs', 'Login'],
    contentOpportunities: ['comparison pages', 'integration guides', 'changelog', 'help center'],
    conversions: ['free trial signup', 'demo request', 'paid subscription'],
    valuePropositions: [
      'saves time',
      'reduces cost',
      'scales with you',
      'integrates with your stack',
    ],
  },
  {
    id: 'professional-services',
    name: 'Professional Services',
    keywords: ['consulting', 'agency', 'services', 'advisory', 'firm', 'professional'],
    businessModels: ['retainer', 'project-based', 'hourly'],
    typicalPages: ['home', 'services', 'about', 'case-studies', 'team', 'blog', 'contact'],
    typicalFeatures: ['contact-forms', 'booking', 'newsletter', 'analytics'],
    trustSignals: [
      'client logos',
      'case studies',
      'certifications',
      'team credentials',
      'testimonials',
    ],
    seoTopics: ['service pages', 'local SEO', 'industry expertise', 'thought leadership'],
    competitorNavigation: ['Services', 'Work', 'About', 'Insights', 'Contact'],
    contentOpportunities: ['service detail pages', 'case study library', 'insights blog'],
    conversions: ['consultation request', 'contact form', 'proposal request'],
    valuePropositions: ['proven expertise', 'measurable outcomes', 'trusted partner'],
  },
  {
    id: 'legal',
    name: 'Legal',
    keywords: ['law', 'legal', 'attorney', 'lawyer', 'solicitor', 'law firm', 'counsel'],
    businessModels: ['hourly', 'retainer', 'contingency'],
    typicalPages: [
      'home',
      'practice-areas',
      'about',
      'attorneys',
      'case-studies',
      'blog',
      'contact',
    ],
    typicalFeatures: ['contact-forms', 'booking', 'analytics'],
    trustSignals: ['bar admissions', 'awards', 'client results', 'attorney bios', 'testimonials'],
    seoTopics: ['practice areas', 'local legal SEO', 'legal guides', 'FAQ by matter'],
    competitorNavigation: ['Practice Areas', 'Attorneys', 'Results', 'About', 'Contact'],
    contentOpportunities: ['practice-area pages', 'legal FAQ', 'case results', 'client guides'],
    conversions: ['case evaluation request', 'consultation booking', 'contact form'],
    valuePropositions: ['experienced counsel', 'proven results', 'client-first representation'],
  },
  {
    id: 'finance',
    name: 'Finance',
    keywords: ['finance', 'bank', 'investment', 'fintech', 'insurance', 'wealth', 'accounting'],
    businessModels: ['fee-based', 'commission', 'subscription'],
    typicalPages: ['home', 'services', 'about', 'pricing', 'resources', 'blog', 'contact', 'login'],
    typicalFeatures: ['authentication', 'contact-forms', 'analytics', 'newsletter'],
    trustSignals: ['regulatory compliance', 'security', 'certifications', 'client testimonials'],
    seoTopics: ['financial guides', 'calculators', 'regulation explainers', 'comparisons'],
    competitorNavigation: ['Products', 'Solutions', 'Resources', 'About', 'Login'],
    contentOpportunities: ['financial calculators', 'guides', 'glossary', 'market insights'],
    conversions: ['account application', 'consultation request', 'quote request'],
    valuePropositions: ['secure and compliant', 'expert guidance', 'transparent pricing'],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    keywords: ['health', 'medical', 'clinic', 'doctor', 'dental', 'wellness', 'therapy', 'care'],
    businessModels: ['appointment-based', 'membership', 'insurance-billed'],
    typicalPages: ['home', 'services', 'about', 'team', 'appointments', 'blog', 'contact'],
    typicalFeatures: ['booking', 'contact-forms', 'maps', 'analytics'],
    trustSignals: ['credentials', 'accreditations', 'patient reviews', 'insurance accepted'],
    seoTopics: ['conditions treated', 'procedures', 'local health SEO', 'patient education'],
    competitorNavigation: ['Services', 'Providers', 'Patients', 'About', 'Book'],
    contentOpportunities: ['condition pages', 'procedure guides', 'patient FAQ'],
    conversions: ['appointment booking', 'contact form', 'new patient registration'],
    valuePropositions: ['expert care', 'patient-centered', 'convenient access'],
  },
  {
    id: 'ecommerce',
    name: 'E-commerce',
    keywords: [
      'shop',
      'store',
      'ecommerce',
      'e-commerce',
      'retail',
      'products',
      'cart',
      'checkout',
    ],
    businessModels: ['direct-to-consumer', 'marketplace', 'subscription-box'],
    typicalPages: [
      'home',
      'products',
      'product-detail',
      'cart',
      'checkout',
      'about',
      'contact',
      'account',
    ],
    typicalFeatures: [
      'payments',
      'search',
      'filtering',
      'authentication',
      'newsletter',
      'analytics',
    ],
    trustSignals: ['reviews', 'secure checkout', 'return policy', 'shipping info', 'ratings'],
    seoTopics: ['product categories', 'buying guides', 'comparisons', 'seasonal content'],
    competitorNavigation: ['Shop', 'Categories', 'Deals', 'About', 'Cart', 'Account'],
    contentOpportunities: ['category pages', 'buying guides', 'product reviews', 'lookbooks'],
    conversions: ['add to cart', 'checkout', 'newsletter signup'],
    valuePropositions: ['quality products', 'fast shipping', 'easy returns'],
  },
  {
    id: 'education',
    name: 'Education',
    keywords: [
      'education',
      'school',
      'course',
      'learning',
      'academy',
      'training',
      'university',
      'edtech',
    ],
    businessModels: ['tuition', 'subscription', 'course-sales'],
    typicalPages: ['home', 'courses', 'about', 'pricing', 'blog', 'faq', 'contact', 'login'],
    typicalFeatures: ['authentication', 'payments', 'search', 'newsletter', 'analytics'],
    trustSignals: ['accreditation', 'outcomes', 'instructor bios', 'student testimonials'],
    seoTopics: ['course topics', 'career guides', 'how-to content', 'curriculum'],
    competitorNavigation: ['Courses', 'Programs', 'About', 'Resources', 'Login'],
    contentOpportunities: ['course catalog', 'learning guides', 'success stories'],
    conversions: ['course enrollment', 'trial signup', 'info request'],
    valuePropositions: ['proven outcomes', 'expert instructors', 'flexible learning'],
  },
  {
    id: 'agency',
    name: 'Creative Agency',
    keywords: ['agency', 'studio', 'creative', 'design', 'branding', 'marketing', 'portfolio'],
    businessModels: ['project-based', 'retainer'],
    typicalPages: ['home', 'work', 'services', 'about', 'blog', 'contact'],
    typicalFeatures: ['contact-forms', 'newsletter', 'analytics'],
    trustSignals: ['portfolio', 'client logos', 'awards', 'case studies'],
    seoTopics: ['service pages', 'portfolio SEO', 'creative insights'],
    competitorNavigation: ['Work', 'Services', 'Studio', 'Journal', 'Contact'],
    contentOpportunities: ['case studies', 'portfolio pieces', 'design journal'],
    conversions: ['project inquiry', 'contact form'],
    valuePropositions: ['award-winning work', 'distinctive craft', 'strategic partner'],
  },
  {
    id: 'hospitality',
    name: 'Hospitality',
    keywords: [
      'restaurant',
      'hotel',
      'cafe',
      'travel',
      'tourism',
      'booking',
      'venue',
      'hospitality',
    ],
    businessModels: ['reservation-based', 'membership'],
    typicalPages: ['home', 'about', 'menu', 'gallery', 'reservations', 'contact'],
    typicalFeatures: ['booking', 'maps', 'contact-forms', 'analytics'],
    trustSignals: ['reviews', 'ratings', 'photos', 'awards'],
    seoTopics: ['local SEO', 'menu content', 'events', 'location guides'],
    competitorNavigation: ['Menu', 'About', 'Gallery', 'Reservations', 'Contact'],
    contentOpportunities: ['menu pages', 'event pages', 'local guides'],
    conversions: ['reservation', 'booking', 'contact'],
    valuePropositions: ['memorable experience', 'quality and care', 'convenient location'],
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    keywords: ['real estate', 'property', 'realty', 'homes', 'listings', 'rentals', 'broker'],
    businessModels: ['commission', 'listing-fee'],
    typicalPages: ['home', 'listings', 'property-detail', 'about', 'agents', 'contact'],
    typicalFeatures: ['search', 'filtering', 'maps', 'contact-forms', 'analytics'],
    trustSignals: ['agent credentials', 'sold listings', 'reviews', 'local expertise'],
    seoTopics: ['neighborhood guides', 'property types', 'local market SEO'],
    competitorNavigation: ['Buy', 'Sell', 'Listings', 'Agents', 'Contact'],
    contentOpportunities: ['neighborhood guides', 'market reports', 'buying guides'],
    conversions: ['listing inquiry', 'viewing request', 'valuation request'],
    valuePropositions: ['local expertise', 'proven sales', 'personal service'],
  },
  {
    id: 'nonprofit',
    name: 'Nonprofit',
    keywords: ['nonprofit', 'charity', 'ngo', 'foundation', 'cause', 'donate', 'volunteer'],
    businessModels: ['donation', 'grant', 'membership'],
    typicalPages: ['home', 'about', 'programs', 'impact', 'donate', 'blog', 'contact'],
    typicalFeatures: ['payments', 'contact-forms', 'newsletter', 'analytics'],
    trustSignals: ['impact metrics', 'transparency reports', 'partner logos', 'stories'],
    seoTopics: ['cause awareness', 'impact stories', 'how to help'],
    competitorNavigation: ['About', 'Programs', 'Impact', 'Donate', 'Get Involved'],
    contentOpportunities: ['impact stories', 'program pages', 'annual reports'],
    conversions: ['donation', 'volunteer signup', 'newsletter signup'],
    valuePropositions: ['real impact', 'transparent stewardship', 'join the cause'],
  },
  GENERIC_PROFILE,
];
