import type { GeneratedFile } from '@cef/core';
import { StyleTemplateBuilder } from '@cef/design-system';
import type { GenerationContext } from '../models/index.js';
import { projectSlug } from '../models/index.js';

/**
 * Stage 1 builder. Lays down the project's architecture from the blueprint: the Next.js App Router
 * skeleton, TypeScript and Tailwind configuration, and `app/globals.css` seeded with the design
 * system's tokens and theme. Everything downstream builds on this foundation.
 */
export class ArchitectureBuilder {
  private readonly styles = new StyleTemplateBuilder();

  build(context: GenerationContext): readonly GeneratedFile[] {
    const slug = projectSlug(context.options.projectName);
    return [
      { path: 'package.json', content: this.packageJson(slug) },
      { path: 'tsconfig.json', content: TSCONFIG },
      { path: 'next.config.mjs', content: NEXT_CONFIG },
      { path: 'postcss.config.mjs', content: POSTCSS },
      { path: 'tailwind.config.ts', content: TAILWIND },
      { path: 'app/globals.css', content: this.globals(context) },
      { path: 'lib/cn.ts', content: CN },
      { path: '.gitignore', content: GITIGNORE },
      { path: '.env.example', content: this.env(context.options.baseUrl) },
      { path: 'README.md', content: this.readme(context.options.projectName) },
    ];
  }

  private globals(context: GenerationContext): string {
    return `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n${this.styles.build({
      tokens: context.tokens,
      theme: context.theme,
    })}`;
  }

  private packageJson(slug: string): string {
    return `${JSON.stringify(
      {
        name: slug,
        version: '0.1.0',
        private: true,
        type: 'module',
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
          lint: 'next lint',
          typecheck: 'tsc --noEmit',
        },
        dependencies: {
          next: '^15.0.0',
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          clsx: '^2.1.1',
          'tailwind-merge': '^2.5.4',
          'class-variance-authority': '^0.7.1',
          'lucide-react': '^0.454.0',
        },
        devDependencies: {
          typescript: '^5.6.0',
          '@types/node': '^22.0.0',
          '@types/react': '^19.0.0',
          '@types/react-dom': '^19.0.0',
          tailwindcss: '^3.4.14',
          postcss: '^8.4.47',
          autoprefixer: '^10.4.20',
        },
      },
      null,
      2,
    )}\n`;
  }

  private env(baseUrl: string): string {
    return `# Public base URL, used for canonical URLs, sitemap, and Open Graph.\nNEXT_PUBLIC_SITE_URL=${baseUrl}\n`;
  }

  private readme(projectName: string): string {
    return [
      `# ${projectName}`,
      '',
      'Generated by the CEF generation pipeline. Every file traces to the project blueprint.',
      '',
      '## Getting started',
      '',
      '```bash',
      'npm install',
      'npm run dev',
      '```',
      '',
      'Design tokens live in `app/globals.css` as CSS custom properties. Components read tokens,',
      'never hard-coded values.',
      '',
    ].join('\n');
  }
}

const TSCONFIG = `${JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'ES2022'],
      module: 'esnext',
      moduleResolution: 'bundler',
      jsx: 'preserve',
      strict: true,
      noUncheckedIndexedAccess: true,
      esModuleInterop: true,
      skipLibCheck: true,
      allowJs: true,
      incremental: true,
      noEmit: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  },
  null,
  2,
)}\n`;

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Self-contained server build — required for the deploy Dockerfile.
  output: 'standalone',
  images: { formats: ['image/avif', 'image/webp'] },
};

export default nextConfig;
`;

const POSTCSS = `export default {
  plugins: { tailwindcss: {}, autoprefixer: {} },
};
`;

const TAILWIND = `import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './content/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--cef-background)',
        surface: 'var(--cef-surface)',
        foreground: 'var(--cef-foreground)',
        primary: 'var(--cef-primary)',
        'primary-foreground': 'var(--cef-primary-foreground)',
        border: 'var(--cef-border)',
      },
    },
  },
  plugins: [],
};

export default config;
`;

const CN = `import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

/** Merge class names, resolving Tailwind conflicts. */
export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
`;

const GITIGNORE = `node_modules
.next
out
.env
.env.local
*.tsbuildinfo
next-env.d.ts
`;
