import type {
  ComponentCategory,
  ComponentDescriptor,
  Complexity,
  Framework,
  Slot,
} from './types.js';

const ALL_FRAMEWORKS: readonly Framework[] = ['nextjs', 'react'];

interface CompInput {
  readonly id: string;
  readonly name: string;
  readonly category: ComponentCategory;
  readonly description: string;
  readonly variants: readonly string[];
  readonly slots: readonly Slot[];
  readonly compositionRules: readonly string[];
  readonly dependencies?: readonly string[];
  readonly accessibilityNotes: readonly string[];
  readonly seoNotes?: readonly string[];
  readonly animation: readonly string[];
  readonly responsiveBehaviour: string;
  readonly complexity: Complexity;
}

function comp(input: CompInput): ComponentDescriptor {
  return {
    id: input.id,
    name: input.name,
    category: input.category,
    description: input.description,
    variants: input.variants,
    slots: input.slots,
    compositionRules: input.compositionRules,
    dependencies: input.dependencies ?? [],
    accessibilityNotes: input.accessibilityNotes,
    seoNotes: input.seoNotes ?? [],
    animation: { supported: input.animation.length > 0, presets: input.animation },
    responsiveBehaviour: input.responsiveBehaviour,
    supportedFrameworks: ALL_FRAMEWORKS,
    complexity: input.complexity,
  };
}

const slot = (name: string, required: boolean, description: string): Slot => ({
  name,
  required,
  description,
});

/** The approved component catalog — the single source components are drawn from. */
export const COMPONENT_CATALOG: readonly ComponentDescriptor[] = [
  comp({
    id: 'hero',
    name: 'Hero',
    category: 'hero',
    description: 'Above-the-fold value proposition with a single primary call to action.',
    variants: ['centered', 'split', 'media-right', 'minimal'],
    slots: [
      slot('headline', true, 'The value proposition'),
      slot('subhead', false, 'One supporting line'),
      slot('primaryCta', true, 'The single primary action'),
      slot('media', false, 'LCP image or product shot'),
    ],
    compositionRules: [
      'Exactly one primary CTA.',
      'Media, when present, is the LCP priority image.',
      'Headline maps to the single page h1.',
    ],
    accessibilityNotes: ['One h1', 'CTA is a real button or link'],
    seoNotes: ['Headline carries the primary keyword', 'h1 present exactly once'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Split collapses to stacked single column on mobile.',
    complexity: 'medium',
  }),
  comp({
    id: 'navbar',
    name: 'Navbar',
    category: 'navigation',
    description: 'Primary site navigation with responsive disclosure.',
    variants: ['simple', 'with-dropdowns', 'centered-logo', 'sticky'],
    slots: [
      slot('logo', true, 'Brand mark linking home'),
      slot('links', true, '5–7 primary destinations'),
      slot('actions', false, 'Auth or CTA buttons'),
    ],
    compositionRules: [
      'Wrapped in a nav landmark.',
      '5–7 primary items; overflow to a menu.',
      'Active item marked with aria-current.',
    ],
    dependencies: ['button'],
    accessibilityNotes: [
      'nav landmark',
      'Mobile disclosure manages focus',
      'Skip link precedes it',
    ],
    seoNotes: ['Descriptive internal links'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Collapses to an accessible hamburger disclosure below md.',
    complexity: 'high',
  }),
  comp({
    id: 'footer',
    name: 'Footer',
    category: 'navigation',
    description: 'Site-wide footer with navigation, legal links, and metadata.',
    variants: ['simple', 'multi-column', 'with-newsletter'],
    slots: [
      slot('columns', true, 'Grouped link columns'),
      slot('legal', true, 'Legal and policy links'),
      slot('social', false, 'Social links'),
    ],
    compositionRules: ['Wrapped in a footer landmark.', 'Includes required legal links.'],
    accessibilityNotes: ['footer landmark', 'Descriptive link text'],
    seoNotes: ['Internal links aid crawling'],
    animation: [],
    responsiveBehaviour: 'Columns stack vertically on mobile.',
    complexity: 'low',
  }),
  comp({
    id: 'card',
    name: 'Cards',
    category: 'content',
    description: 'A reusable content card with consistent slots.',
    variants: ['default', 'bordered', 'elevated', 'interactive'],
    slots: [
      slot('media', false, 'Optional image'),
      slot('title', true, 'Card title'),
      slot('body', false, 'Supporting copy'),
      slot('action', false, 'Single primary target'),
    ],
    compositionRules: ['One primary target per card.', 'Consistent slot order across a grid.'],
    accessibilityNotes: ['Single clear target', 'No nested conflicting links'],
    animation: ['hover-lift'],
    responsiveBehaviour: 'Grid reflows from multi-column to single column.',
    complexity: 'low',
  }),
  comp({
    id: 'testimonials',
    name: 'Testimonials',
    category: 'social-proof',
    description: 'Real customer quotes with attribution.',
    variants: ['grid', 'single-quote', 'carousel-controlled'],
    slots: [
      slot('quote', true, 'The testimonial text'),
      slot('author', true, 'Name and role'),
      slot('avatar', false, 'Author image'),
    ],
    compositionRules: ['Only real testimonials.', 'Carousel is user-controlled, never auto.'],
    accessibilityNotes: ['blockquote with cite', 'Controls are keyboard operable'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Grid collapses to a single column on mobile.',
    complexity: 'medium',
  }),
  comp({
    id: 'pricing',
    name: 'Pricing',
    category: 'commerce',
    description: 'Pricing tiers with a recommended plan and feature comparison.',
    variants: ['tiers', 'comparison-table', 'toggle-billing'],
    slots: [
      slot('tiers', true, 'Plan cards'),
      slot('features', true, 'Per-tier feature list'),
      slot('cta', true, 'Per-tier action'),
    ],
    compositionRules: [
      'One recommended tier emphasized.',
      'Real prices only, no invented numbers.',
    ],
    dependencies: ['card', 'button'],
    accessibilityNotes: ['Tabular data uses table semantics', 'Toggle is a labelled control'],
    seoNotes: ['Product/Offer JSON-LD where applicable'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Tiers stack; comparison table scrolls within its own container.',
    complexity: 'high',
  }),
  comp({
    id: 'timeline',
    name: 'Timeline',
    category: 'content',
    description: 'Ordered sequence of events or steps.',
    variants: ['vertical', 'horizontal', 'alternating'],
    slots: [slot('items', true, 'Ordered entries with a time and description')],
    compositionRules: ['Uses an ordered list.', 'Chronological order preserved.'],
    accessibilityNotes: ['ol semantics', 'Not conveyed by color alone'],
    animation: ['reveal-on-scroll'],
    responsiveBehaviour: 'Horizontal collapses to vertical on mobile.',
    complexity: 'medium',
  }),
  comp({
    id: 'faq',
    name: 'FAQ',
    category: 'content',
    description: 'Question-and-answer accordion.',
    variants: ['accordion', 'two-column', 'grouped'],
    slots: [slot('items', true, 'Question and answer pairs')],
    compositionRules: ['Questions are headings.', 'Answers front-load the response.'],
    accessibilityNotes: ['Disclosure pattern with aria-expanded', 'Keyboard operable'],
    seoNotes: ['FAQPage JSON-LD', 'Question-shaped headings'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Two-column collapses to a single column.',
    complexity: 'medium',
  }),
  comp({
    id: 'features',
    name: 'Features',
    category: 'content',
    description: 'Product features with icons and descriptions.',
    variants: ['grid', 'alternating-media', 'list'],
    slots: [slot('items', true, 'Feature entries'), slot('media', false, 'Supporting visual')],
    compositionRules: [
      'Content-driven count, never a default three-card row.',
      'Icons are labelled.',
    ],
    accessibilityNotes: ['Icons paired with text', 'Meaningful heading order'],
    animation: ['reveal-on-scroll'],
    responsiveBehaviour: 'Grid reflows to fewer columns then stacks.',
    complexity: 'medium',
  }),
  comp({
    id: 'gallery',
    name: 'Gallery',
    category: 'media',
    description: 'Image gallery with an accessible lightbox.',
    variants: ['grid', 'masonry', 'carousel-controlled'],
    slots: [slot('images', true, 'Sized, alt-described images')],
    compositionRules: ['All images sized to prevent CLS.', 'Lightbox traps and restores focus.'],
    accessibilityNotes: ['Meaningful alt text', 'Lightbox is keyboard operable'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Column count adapts to viewport.',
    complexity: 'high',
  }),
  comp({
    id: 'contact',
    name: 'Contact',
    category: 'form',
    description: 'Contact section with a validated form and details.',
    variants: ['form-only', 'split-with-map', 'with-details'],
    slots: [slot('form', true, 'The contact form'), slot('details', false, 'Address and hours')],
    compositionRules: ['Server-validated submission.', 'Inputs retain values on error.'],
    dependencies: ['form'],
    accessibilityNotes: ['Labelled fields', 'Inline, tied error messages'],
    animation: [],
    responsiveBehaviour: 'Split collapses to stacked on mobile.',
    complexity: 'medium',
  }),
  comp({
    id: 'form',
    name: 'Forms',
    category: 'form',
    description: 'General form primitive with validation and states.',
    variants: ['single-column', 'multi-step', 'inline'],
    slots: [slot('fields', true, 'Labelled inputs'), slot('submit', true, 'Submit control')],
    compositionRules: [
      'Visible labels, never placeholder-as-label.',
      'Loading and result states present.',
    ],
    accessibilityNotes: ['label association', 'aria-required', 'Correct input types'],
    animation: [],
    responsiveBehaviour: 'Inputs are at least 44px tall on touch.',
    complexity: 'medium',
  }),
  comp({
    id: 'blog-card',
    name: 'Blog Cards',
    category: 'content',
    description: 'Article preview card for listings.',
    variants: ['default', 'featured', 'horizontal'],
    slots: [
      slot('cover', false, 'Cover image'),
      slot('title', true, 'Article title'),
      slot('excerpt', false, 'Short summary'),
      slot('meta', false, 'Author and date'),
    ],
    compositionRules: ['Whole card links to the article.', 'Title is a descriptive link.'],
    dependencies: ['card'],
    accessibilityNotes: ['Single link target', 'Descriptive anchor text'],
    seoNotes: ['Article JSON-LD on the target page'],
    animation: ['hover-lift'],
    responsiveBehaviour: 'Horizontal collapses to stacked on mobile.',
    complexity: 'low',
  }),
  comp({
    id: 'cta',
    name: 'CTA',
    category: 'cta',
    description: 'Focused conversion band with a single action.',
    variants: ['centered', 'split', 'banner'],
    slots: [slot('headline', true, 'The ask'), slot('action', true, 'Single primary CTA')],
    compositionRules: ['Exactly one primary action.', 'Generous surrounding whitespace.'],
    dependencies: ['button'],
    accessibilityNotes: ['Action is a real control', 'Sufficient contrast'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Split stacks on mobile.',
    complexity: 'low',
  }),
  comp({
    id: 'stats',
    name: 'Stats',
    category: 'social-proof',
    description: 'Key metrics presented as a scannable row.',
    variants: ['row', 'grid', 'with-icons'],
    slots: [slot('items', true, 'Real metrics with labels')],
    compositionRules: ['Only verified numbers.', 'Tabular numerals for alignment.'],
    accessibilityNotes: ['Not conveyed by color alone'],
    animation: ['reveal-on-scroll'],
    responsiveBehaviour: 'Row wraps to a grid then stacks.',
    complexity: 'low',
  }),
  comp({
    id: 'logos',
    name: 'Logos',
    category: 'social-proof',
    description: 'Customer or partner logo wall.',
    variants: ['grid', 'row'],
    slots: [slot('logos', true, 'Real, permitted logos')],
    compositionRules: ['Static, legible grid — never an infinite marquee.'],
    accessibilityNotes: ['Each logo has descriptive alt text'],
    animation: [],
    responsiveBehaviour: 'Grid column count adapts to viewport.',
    complexity: 'low',
  }),
  comp({
    id: 'team',
    name: 'Team',
    category: 'content',
    description: 'Team member cards with roles.',
    variants: ['grid', 'list', 'with-bio'],
    slots: [
      slot('members', true, 'People with name, role, photo'),
      slot('bio', false, 'Optional biography'),
    ],
    compositionRules: ['Real people and photos only.'],
    dependencies: ['card'],
    accessibilityNotes: ['Photos have descriptive alt', 'Semantic headings'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Grid reflows then stacks.',
    complexity: 'low',
  }),
  comp({
    id: 'dashboard-widget',
    name: 'Dashboard Widgets',
    category: 'admin',
    description: 'Composable dashboard tiles (KPIs, lists, activity).',
    variants: ['kpi', 'list', 'activity', 'progress'],
    slots: [slot('title', true, 'Widget title'), slot('content', true, 'Widget body')],
    compositionRules: ['One responsibility per widget.', 'All states handled.'],
    accessibilityNotes: ['Live regions for updates', 'Keyboard operable controls'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Reflows across a dense grid.',
    complexity: 'medium',
  }),
  comp({
    id: 'table',
    name: 'Tables',
    category: 'data',
    description: 'Data table with sorting, pagination, and empty states.',
    variants: ['simple', 'sortable', 'paginated', 'selectable'],
    slots: [slot('columns', true, 'Column definitions'), slot('rows', true, 'Row data')],
    compositionRules: ['Server pagination for large sets.', 'Explicit empty state.'],
    accessibilityNotes: ['table/th/scope semantics', 'Sort state announced'],
    animation: [],
    responsiveBehaviour: 'Scrolls within its own container; never overflows the body.',
    complexity: 'high',
  }),
  comp({
    id: 'chart',
    name: 'Charts',
    category: 'data',
    description: 'Accessible data visualizations.',
    variants: ['line', 'bar', 'area', 'donut'],
    slots: [slot('series', true, 'Data series'), slot('legend', false, 'Series legend')],
    compositionRules: ['Data has an accessible text alternative.', 'Not conveyed by color alone.'],
    accessibilityNotes: ['Text summary or data table alternative', 'Distinguishable series'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Resizes to container; legend wraps.',
    complexity: 'high',
  }),
  comp({
    id: 'auth',
    name: 'Authentication',
    category: 'auth',
    description: 'Sign-in, sign-up, and recovery forms.',
    variants: ['sign-in', 'sign-up', 'reset-password', 'oauth'],
    slots: [slot('form', true, 'Credential form'), slot('providers', false, 'OAuth providers')],
    compositionRules: [
      'Server-side validation and rate limiting.',
      'Never store secrets client-side.',
    ],
    dependencies: ['form', 'button'],
    accessibilityNotes: ['Labelled fields', 'Errors are specific and tied'],
    animation: [],
    responsiveBehaviour: 'Single-column, centered, thumb-reachable actions.',
    complexity: 'high',
  }),
  comp({
    id: 'commerce',
    name: 'Commerce',
    category: 'commerce',
    description: 'Product cards, cart, and checkout building blocks.',
    variants: ['product-card', 'product-grid', 'cart', 'checkout'],
    slots: [
      slot('product', true, 'Product data'),
      slot('price', true, 'Price and currency'),
      slot('action', true, 'Add-to-cart or buy'),
    ],
    compositionRules: ['Real product data.', 'Server-validated, idempotent mutations.'],
    dependencies: ['card', 'button', 'form'],
    accessibilityNotes: ['Price is not color-only', 'Cart updates announced'],
    seoNotes: ['Product JSON-LD', 'Canonical product URLs'],
    animation: ['hover-lift'],
    responsiveBehaviour: 'Grid reflows; checkout is single-column on mobile.',
    complexity: 'high',
  }),
  comp({
    id: 'admin',
    name: 'Admin Components',
    category: 'admin',
    description: 'Admin shell primitives: sidebar, toolbar, data views.',
    variants: ['sidebar', 'toolbar', 'data-view', 'detail-panel'],
    slots: [slot('navigation', true, 'Admin navigation'), slot('content', true, 'Routed region')],
    compositionRules: [
      'Persistent navigation plus a routed content region.',
      'All states handled.',
    ],
    dependencies: ['table', 'dashboard-widget'],
    accessibilityNotes: ['Landmarks and skip links', 'Keyboard operable throughout'],
    animation: ['fade-in'],
    responsiveBehaviour: 'Sidebar collapses to a disclosure on small screens.',
    complexity: 'high',
  }),
  comp({
    id: 'button',
    name: 'Button',
    category: 'cta',
    description: 'The primary action primitive with defined variants and states.',
    variants: ['primary', 'secondary', 'ghost', 'outline', 'danger'],
    slots: [
      slot('label', true, 'Verb-led action text'),
      slot('icon', false, 'Optional leading icon'),
    ],
    compositionRules: [
      'Exactly one primary per view.',
      'All states: default, hover, focus, active, disabled, loading.',
    ],
    accessibilityNotes: ['Real button/a element', 'Icon-only variant has an accessible name'],
    animation: ['button-press'],
    responsiveBehaviour: 'Minimum 44px touch target.',
    complexity: 'low',
  }),
];
