import type { DesignPreset } from './types.js';

/** The design presets — named, coherent stylistic systems applied over the base tokens. */
export const PRESET_CATALOG: readonly DesignPreset[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Restrained, whitespace-forward, near-monochrome.',
    typography: { ratio: 'minorThird', pairingId: 'inter-inter' },
    spacingDensity: 'spacious',
    motionStyle: 'restrained',
    componentStyle: { radius: 'sharp', button: 'outline', elevation: 'flat' },
    gridColumns: 12,
    colorStrategy: 'monochrome',
  },
  {
    id: 'premium',
    name: 'Premium',
    description: 'Confident hierarchy, generous space, subtle depth.',
    typography: { ratio: 'majorThird', pairingId: 'fraunces-inter' },
    spacingDensity: 'spacious',
    motionStyle: 'balanced',
    componentStyle: { radius: 'rounded', button: 'solid', elevation: 'subtle' },
    gridColumns: 12,
    colorStrategy: 'duotone',
  },
  {
    id: 'luxury',
    name: 'Luxury',
    description: 'Editorial serif display, quiet palette, sharp corners.',
    typography: { ratio: 'goldenRatio', pairingId: 'playfair-source' },
    spacingDensity: 'spacious',
    motionStyle: 'restrained',
    componentStyle: { radius: 'sharp', button: 'outline', elevation: 'flat' },
    gridColumns: 12,
    colorStrategy: 'muted',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Dense, dependable, information-first.',
    typography: { ratio: 'minorThird', pairingId: 'lora-inter' },
    spacingDensity: 'compact',
    motionStyle: 'restrained',
    componentStyle: { radius: 'rounded', button: 'soft', elevation: 'subtle' },
    gridColumns: 12,
    colorStrategy: 'duotone',
  },
  {
    id: 'modern',
    name: 'Modern',
    description: 'Clean sans, comfortable rhythm, soft depth.',
    typography: { ratio: 'majorThird', pairingId: 'inter-inter' },
    spacingDensity: 'comfortable',
    motionStyle: 'balanced',
    componentStyle: { radius: 'rounded', button: 'solid', elevation: 'subtle' },
    gridColumns: 12,
    colorStrategy: 'duotone',
  },
  {
    id: 'editorial',
    name: 'Editorial',
    description: 'Magazine hierarchy, serif headings, long-form measure.',
    typography: { ratio: 'perfectFourth', pairingId: 'fraunces-inter' },
    spacingDensity: 'comfortable',
    motionStyle: 'restrained',
    componentStyle: { radius: 'sharp', button: 'outline', elevation: 'flat' },
    gridColumns: 12,
    colorStrategy: 'muted',
  },
  {
    id: 'bold',
    name: 'Bold',
    description: 'Large type, high contrast, expressive motion.',
    typography: { ratio: 'goldenRatio', pairingId: 'space-grotesk-inter' },
    spacingDensity: 'comfortable',
    motionStyle: 'expressive',
    componentStyle: { radius: 'pill', button: 'solid', elevation: 'pronounced' },
    gridColumns: 12,
    colorStrategy: 'vibrant',
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Refined serif, airy spacing, gentle motion.',
    typography: { ratio: 'majorThird', pairingId: 'playfair-source' },
    spacingDensity: 'spacious',
    motionStyle: 'balanced',
    componentStyle: { radius: 'rounded', button: 'soft', elevation: 'subtle' },
    gridColumns: 12,
    colorStrategy: 'muted',
  },
  {
    id: 'tech',
    name: 'Tech',
    description: 'Grotesk display, tight grid, precise motion.',
    typography: { ratio: 'majorThird', pairingId: 'space-grotesk-inter' },
    spacingDensity: 'comfortable',
    motionStyle: 'balanced',
    componentStyle: { radius: 'rounded', button: 'solid', elevation: 'subtle' },
    gridColumns: 12,
    colorStrategy: 'duotone',
  },
  {
    id: 'creative',
    name: 'Creative',
    description: 'Playful scale, rounded forms, expressive motion.',
    typography: { ratio: 'perfectFourth', pairingId: 'space-grotesk-inter' },
    spacingDensity: 'comfortable',
    motionStyle: 'expressive',
    componentStyle: { radius: 'pill', button: 'solid', elevation: 'pronounced' },
    gridColumns: 12,
    colorStrategy: 'vibrant',
  },
];
