import type { Animation, Framework } from '@cef/core';
import type { TemplateContext } from '../context.js';
import { jsonFile, sortedRecord } from './util.js';

interface FrameworkPreset {
  readonly dependencies: Record<string, string>;
  readonly devDependencies: Record<string, string>;
  readonly scripts: Record<string, string>;
}

const FRAMEWORK_PRESETS: Record<Framework, FrameworkPreset> = {
  nextjs: {
    dependencies: { next: '^15.1.0', react: '^19.0.0', 'react-dom': '^19.0.0' },
    devDependencies: {},
    scripts: { dev: 'next dev', build: 'next build', start: 'next start', lint: 'next lint' },
  },
  react: {
    dependencies: { react: '^19.0.0', 'react-dom': '^19.0.0' },
    devDependencies: { vite: '^6.0.0', '@vitejs/plugin-react': '^4.3.4' },
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
  },
  astro: {
    dependencies: { astro: '^5.1.0' },
    devDependencies: {},
    scripts: { dev: 'astro dev', build: 'astro build', preview: 'astro preview' },
  },
  remix: {
    dependencies: {
      '@remix-run/node': '^2.15.0',
      '@remix-run/react': '^2.15.0',
      '@remix-run/serve': '^2.15.0',
      react: '^18.3.1',
      'react-dom': '^18.3.1',
    },
    devDependencies: { '@remix-run/dev': '^2.15.0', vite: '^6.0.0' },
    scripts: {
      dev: 'remix vite:dev',
      build: 'remix vite:build',
      start: 'remix-serve ./build/server/index.js',
    },
  },
};

const ANIMATION_DEPS: Record<Animation, Record<string, string>> = {
  'framer-motion': { 'framer-motion': '^11.15.0' },
  'motion-one': { motion: '^11.15.0' },
  gsap: { gsap: '^3.12.5' },
  none: {},
};

export function packageJson(ctx: TemplateContext): string {
  const preset = FRAMEWORK_PRESETS[ctx.spec.framework];
  const dependencies: Record<string, string> = {
    ...preset.dependencies,
    ...ANIMATION_DEPS[ctx.spec.animation],
  };
  const devDependencies: Record<string, string> = { ...preset.devDependencies };

  if (ctx.spec.language === 'typescript') {
    devDependencies['typescript'] = '^5.7.3';
    devDependencies['@types/node'] = '^22.13.0';
  }
  if (ctx.spec.styling === 'tailwind') {
    devDependencies['tailwindcss'] = '^3.4.17';
    devDependencies['postcss'] = '^8.4.49';
    devDependencies['autoprefixer'] = '^10.4.20';
  }

  return jsonFile({
    name: ctx.spec.name,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: preset.scripts,
    dependencies: sortedRecord(dependencies),
    devDependencies: sortedRecord(devDependencies),
  });
}

export function tsconfigJson(): string {
  return jsonFile({
    compilerOptions: {
      target: 'ES2022',
      lib: ['ES2023', 'DOM', 'DOM.Iterable'],
      module: 'ESNext',
      moduleResolution: 'Bundler',
      strict: true,
      noUncheckedIndexedAccess: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      jsx: 'preserve',
      incremental: true,
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      baseUrl: '.',
      paths: { '@/*': ['./*'] },
    },
    include: ['**/*.ts', '**/*.tsx'],
    exclude: ['node_modules', 'dist', '.next', 'build'],
  });
}

export function eslintConfig(): string {
  return `import js from '@eslint/js';
import tseslint from 'typescript-eslint';

// Project ESLint config generated by CEF. Extend as the app grows.
export default tseslint.config(
  { ignores: ['dist/**', '.next/**', 'build/**', 'node_modules/**'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
);
`;
}

export function prettierRc(): string {
  return jsonFile({
    semi: true,
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 100,
    endOfLine: 'lf',
  });
}

export function editorConfig(): string {
  return `root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 2
`;
}

export function gitignore(): string {
  return `# Dependencies
node_modules/
.pnp/
.yarn/

# Build output
dist/
build/
.next/
.astro/
out/
*.tsbuildinfo

# Environment & secrets
.env
.env.*
!.env.example

# Logs & caches
logs/
*.log
.cache/
.eslintcache
coverage/

# OS & editor
.DS_Store
Thumbs.db
.idea/
.vscode/*
!.vscode/extensions.json
`;
}
