import type { Database, Framework } from '@cef/core';
import type { TemplateContext } from '../context.js';

const PORT = 3000;

/** Production start command per framework (the container installs/builds with npm for portability). */
const START_CMD: Record<Framework, string> = {
  nextjs: 'CMD ["npm", "run", "start"]',
  remix: 'CMD ["npm", "run", "start"]',
  astro: 'CMD ["npx", "-y", "serve", "dist", "-l", "3000"]',
  react: 'CMD ["npx", "-y", "serve", "dist", "-s", "-l", "3000"]',
};

export function dockerfile(ctx: TemplateContext): string {
  return `# syntax=docker/dockerfile:1
# Multi-stage image generated by CEF. The container installs and builds with npm for
# portability; the project's preferred package manager is recorded in .cef/project.json.
FROM node:20-alpine AS base
WORKDIR /app

FROM base AS deps
COPY package.json ./
RUN npm install

FROM base AS build
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM base AS runtime
ENV NODE_ENV=production
ENV PORT=${PORT}
COPY --from=build /app ./
EXPOSE ${PORT}
${START_CMD[ctx.spec.framework]}
`;
}

const DB_SERVICES: Partial<Record<Database, string>> = {
  postgres: `  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
`,
  mysql: `  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
`,
  mongodb: `  db:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
`,
};

export function dockerCompose(ctx: TemplateContext): string {
  const dbService = DB_SERVICES[ctx.spec.database];
  const dependsOn = dbService ? '    depends_on:\n      - db\n' : '';
  const services = `  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
${dependsOn}${dbService ?? ''}`;
  const volumes = dbService ? '\nvolumes:\n  db-data:\n' : '\n';
  return `services:
${services}${volumes}`;
}

const DB_URL: Partial<Record<Database, string>> = {
  postgres: 'DATABASE_URL=postgresql://app:app@localhost:5432/app',
  mysql: 'DATABASE_URL=mysql://root:app@localhost:3306/app',
  mongodb: 'DATABASE_URL=mongodb://localhost:27017/app',
  sqlite: 'DATABASE_URL=file:./dev.db',
};

export function envFile(ctx: TemplateContext): string {
  const lines = ['NODE_ENV=development', `PORT=${PORT}`];
  const dbUrl = DB_URL[ctx.spec.database];
  if (dbUrl) {
    lines.push(dbUrl);
  }
  return `${lines.join('\n')}\n`;
}

export function envExample(ctx: TemplateContext): string {
  // Same keys as .env, values blanked — safe to commit.
  return envFile(ctx)
    .split('\n')
    .map((line) => (line.includes('=') ? `${line.split('=')[0]}=` : line))
    .join('\n');
}
